# Generated by Django 6.0.7 on 2026-09-01 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubetto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledtaskhistory',
            index=models.Index(fields=['-started_at'], name='tubetto_sch_started_2011f1_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtaskhistory',
            index=models.Index(fields=['status', 'ended_at'], name='tubetto_sch_status_77f638_idx'),
        ),
    ]
