# Generated by Django 6.0.7 on 2026-09-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubetto', '0002_scheduledtaskhistory_tubetto_sch_started_2011f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtaskhistory',
            name='q_task_id',
            field=models.CharField(blank=True, default='', help_text='Django Q task ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='scheduledtaskhistory',
            name='task_type',
            field=models.CharField(choices=[('update_channels', 'Update Channels Metadata'), ('scan_videos', 'Scan Channel Videos'), ('scan_channel_tabs', 'Scan Channel Tabs'), ('update_videos_metadata', 'Update Videos Metadata'), ('update_music_tracks', 'Update Music Tracks Metadata'), ('run_all', 'All Tasks')], max_length=50),
        ),
    ]
