# Generated by Django 5.2.7 on 2025-11-26 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('yt_channel_id', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('subscriber_count', models.PositiveIntegerField(blank=True, null=True)),
                ('video_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_video_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('channel_external_id', models.CharField(blank=True, max_length=128)),
                ('uploader', models.CharField(blank=True, max_length=255)),
                ('uploader_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_video_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_videos', to='videos.channel')),
            ],
            options={
                'unique_together': {('channel', 'yt_video_id')},
            },
        ),
    ]
