# Generated by Django 5.2.15 on 2026-07-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='yt_channel_url',
            field=models.URLField(blank=True),
        ),
    ]
