# Generated by Django 5.2.7 on 2025-11-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
    ]
