# Generated by Django 5.2.15 on 2026-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_channel_yt_channel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='yt_channel_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
