# Generated by Django 5.2.7 on 2025-11-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_channel_is_whitelisted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
