# Generated by Django 6.0.7 on 2026-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_channel_yt_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_tabs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='yt_channel_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
