# Generated by Django 5.2.7 on 2025-11-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_video_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_videos', to='videos.channel')),
            ],
            options={
                'unique_together': {('channel', 'yt_video_id')},
            },
        ),
    ]
