# Generated by Django 5.2.7 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_channelvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_whitelisted',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_whitelisted',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_at',
        ),
        migrations.AddField(
            model_name='video',
            name='channel_external_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='video',
            name='channel_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='WhitelistEntry',
        ),
    ]
