# Generated by Django 6.0.7 on 2026-08-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_channel_channel_tabs_alter_channel_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_tabs',
        ),
    ]
