# Generated by Django 6.0.7 on 2026-08-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_channel_channel_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_tabs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('featured', 'Home'), ('videos', 'Video'), ('shorts', 'Shorts'), ('streams', 'Live'), ('podcasts', 'Podcast'), ('courses', 'Corsi'), ('playlists', 'Playlist')], max_length=32)),
                ('nome', models.CharField(max_length=255)),
                ('yt_id', models.CharField(blank=True, max_length=128)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='videos.channel')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
                'unique_together': {('channel', 'tipo', 'yt_id')},
            },
        ),
        migrations.CreateModel(
            name='TabVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='videos.tab')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_links', to='videos.video')),
            ],
            options={
                'unique_together': {('video', 'tab')},
            },
        ),
    ]
