# Generated by Django 5.2.7 on 2025-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_channel_created_at_channel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('audio_url', models.URLField(help_text='Direct URL to the audio file (MP3/OGG/etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'artist'),
            },
        ),
    ]
