# Generated by Django 6.0.7 on 2026-08-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_channel_channel_tabs_tab_tabvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_tabs',
        ),
    ]
