# Generated by Django 6.0.7 on 2026-08-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_channel_channel_tabs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='tipo',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together={('channel', 'type', 'yt_id')},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subscriber_count',
        ),
        migrations.AddField(
            model_name='video',
            name='tabs',
            field=models.ManyToManyField(blank=True, related_name='videos', through='videos.TabVideo', to='videos.tab'),
        ),
    ]
