# Generated by Django 5.2.7 on 2025-11-13 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_musictrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV, OGG, FLAC)', upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'flac'])]),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Optional direct URL to stream the audio file'),
        ),
    ]
