# Generated by Django 5.2.7 on 2025-11-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_musictrack_audio_file_alter_musictrack_audio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musictrack',
            options={'ordering': ('title', 'artist', 'yt_video_id')},
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='yt_video_id',
            field=models.CharField(default='', help_text='YouTube video id to extract audio from', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
