# Generated by Django 6.0.7 on 2026-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_tab_options_rename_nome_tab_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title'], name='videos_vide_title_8a2e81_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-upload_date', '-created_at'], name='videos_vide_upload__b3c2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['channel', '-upload_date'], name='videos_vide_channel_23cf44_idx'),
        ),
    ]
