# Generated by Django 5.2.7 on 2025-11-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_musictrack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
