# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_musicplaylist_musicplaylisttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicplaylist',
            name='published_m3u_path',
            field=models.CharField(blank=True, help_text='Path to the published M3U file', max_length=512),
        ),
    ]

